In [19]:
import pandas as pd

In [20]:
df_elections = pd.read_csv('elections_33_clean.csv')
df_population = pd.read_csv('../2-transform/population/combined.csv')
df_scolarité = pd.read_csv('../2-transform/scolarité/combined.csv')

In [21]:
df_elections.head()

,Annee,Code de la commune,Libellé de la commune,Inscrits,Abstentions,Votants,Exprimés,Blancs_et_nuls,Sexe,Nom Complet,Voix,Candidat_ID,Orientation,Pourcentage_Blancs_et_nuls,Pourcentage_Abstentions,Pourcentage_Votants
0,1995,1,ABZAC,1091,195,896,860,36.0,M,LE PEN J.MARIE,143,1,1.0,4.186047,17.873511,82.126489
1,1995,2,AILLAS,530,92,438,424,14.0,M,LE PEN J.MARIE,36,1,1.0,3.301887,17.358491,82.641509
2,1995,3,AMBARES & LAGRAVE,6930,1306,5624,5468,156.0,M,LE PEN J.MARIE,897,1,1.0,2.852963,18.845599,81.154401
3,1995,4,AMBES,1834,295,1539,1506,33.0,M,LE PEN J.MARIE,179,1,1.0,2.191235,16.085060,83.914940
4,1995,5,ANDERNOS LES BAINS,6551,1422,5129,4994,135.0,M,LE PEN J.MARIE,671,1,1.0,2.703244,21.706610,78.293390

In [22]:
df_population.head()

,Pop 15 ans ou plus Hommes Prof. intermédiaires (compl),Pop Hommes 30-44 ans (princ),Code géographique,Pop Femmes 75-89 ans (princ),Pop Hommes 20-64 ans (princ),Pop 15 ans ou plus Femmes Retraités (compl),Pop 15 ans ou plus Hommes Employés (compl),"Pop 15-24 ans Artisans, Comm., Chefs entr. (compl)",Pop 15 ans ou plus Hommes Agriculteurs exploitants (compl),Pop Femmes 30-44 ans (princ),...,Pop Hommes 75-89 ans (princ),Pop Hommes 90 ans ou plus (princ),Pop Hommes 0-14 ans (princ),"Pop 15 ans ou plus Hommes Cadres, Prof. intel. sup. (compl)",Pop 55 ans ou plus Prof. intermédiaires (compl),"Pop 15 ans ou plus Hommes Artisans, Comm., Chefs entr. (compl)",Pop Femmes 0-14 ans (princ),Pop Femmes 15-29 ans (princ),Pop 55 ans ou plus (compl),year
0,61.0,186.0,33001,105.0,500.0,216.0,45.0,0.0,24.0,204.0,...,73.0,5.0,173.0,33.0,16.0,41.0,173.0,125.0,509.0,2009
1,45.0,77.0,33002,45.0,195.0,122.0,4.0,0.0,20.0,77.0,...,41.0,1.0,53.0,4.0,16.0,24.0,64.0,45.0,297.0,2009
2,788.0,1443.0,33003,463.0,3806.0,1109.0,437.0,18.0,10.0,1594.0,...,298.0,8.0,1499.0,398.0,154.0,364.0,1384.0,1108.0,3099.0,2009
3,106.0,284.0,33004,115.0,801.0,336.0,86.0,0.0,0.0,312.0,...,101.0,2.0,361.0,41.0,29.0,41.0,267.0,235.0,829.0,2009
4,540.0,832.0,33005,919.0,2644.0,2220.0,216.0,4.0,28.0,972.0,...,648.0,30.0,807.0,452.0,192.0,236.0,747.0,525.0,5204.0,2009

In [23]:
df_scolarité.head()

,Pop scolarisée 25-29 ans (princ),Hommes 15-17 ans (princ),Hommes scolarisés 11-14 ans (princ),Pop 6-10 ans (princ),Hommes scolarisés 2-5 ans (princ),Hommes scolarisés 6-10 ans (princ),Femmes 15-17 ans (princ),Femmes scolarisées 11-14 ans (princ),Région,Département,...,Pop scolarisée 2-5 ans (princ),Pop scolarisée 11-14 ans (princ),Femmes scolarisées 25-29 ans (princ),Femmes 18-24 ans (princ),Pop 25-29 ans (princ),Hommes 25-29 ans (princ),Femmes 25-29 ans (princ),Hommes scolarisés 25-29 ans (princ),Pop 30 ans ou plus (princ),year
0,2.0,34.0,51.0,102.0,40.0,42.0,34.0,42.0,75,33,...,74.0,93.0,1.0,44.0,95.0,47.0,48.0,1.0,1165.0,2009
1,0.0,8.0,10.0,34.0,17.0,19.0,11.0,19.0,75,33,...,33.0,30.0,0.0,20.0,28.0,15.0,13.0,0.0,550.0,2009
2,29.0,324.0,433.0,1093.0,250.0,572.0,257.0,373.0,75,33,...,499.0,807.0,16.0,466.0,766.0,381.0,385.0,13.0,8006.0,2009
3,1.0,64.0,104.0,228.0,66.0,117.0,45.0,72.0,75,33,...,110.0,177.0,1.0,119.0,124.0,53.0,70.0,0.0,1814.0,2009
4,14.0,177.0,260.0,583.0,140.0,284.0,180.0,234.0,75,33,...,257.0,494.0,9.0,185.0,305.0,145.0,160.0,5.0,8378.0,2009

In [31]:
df_scolarité.columns

Index(['Pop scolarisée 25-29 ans (princ)', 'Hommes 15-17 ans (princ)',
       'Hommes scolarisés 11-14 ans (princ)', 'Pop 6-10 ans (princ)',
       'Hommes scolarisés 2-5 ans (princ)',
       'Hommes scolarisés 6-10 ans (princ)', 'Femmes 15-17 ans (princ)',
       'Femmes scolarisées 11-14 ans (princ)', 'Région', 'Département',
       'Code géographique', 'Pop 15-17 ans (princ)',
       'Femmes scolarisées 30 ans ou plus  (princ)',
       'Pop scolarisée 6-10 ans (princ)', 'Pop 11-14 ans (princ)',
       'Hommes 18-24 ans (princ)', 'Pop scolarisée 30 ans ou plus (princ)',
       'Hommes scolarisés 15-17 ans (princ)', 'Libellé de la commune',
       'Femmes 30 ans ou plus (princ)',
       'Hommes scolarisés 30 ans ou plus (princ)',
       'Pop 15 ans ou plus non scolarisée (princ)', 'Femmes 6-10 ans (princ)',
       'Pop scolarisée 18-24 ans (princ)', 'Pop 18-24 ans (princ)',
       'Femmes 2-5 ans (princ)', 'Femmes 11-14 ans (princ)',
       'Hommes scolarisés 18-24 ans (princ)',
       'Femmes scolarisées 18-24 ans (princ)', 'Hommes 30 ans ou plus (princ)',
       'Femmes scolarisées 2-5 ans (princ)',
       'Pop scolarisée 15-17 ans (princ)',
       'Femmes scolarisées 6-10 ans (princ)',
       'Femmes scolarisées 15-17 ans (princ)', 'Pop 2-5 ans (princ)',
       'Pop scolarisée 2-5 ans (princ)', 'Pop scolarisée 11-14 ans (princ)',
       'Femmes scolarisées 25-29 ans (princ)', 'Femmes 18-24 ans (princ)',
       'Pop 25-29 ans (princ)', 'Hommes 25-29 ans (princ)',
       'Femmes 25-29 ans (princ)', 'Hommes scolarisés 25-29 ans (princ)',
       'Pop 30 ans ou plus (princ)', 'year'],
      dtype='object')

In [46]:
df_pop_scol = pd.merge(df_population, df_scolarité, on=['Code géographique', 'Libellé de la commune', 'year', 'Région', 'Département'])

In [50]:
for col in df_elections:
    print(col)

Annee
Code de la commune
Libellé de la commune
Inscrits
Abstentions
Votants
Exprimés
Blancs_et_nuls
Sexe
Nom Complet
Voix
Candidat_ID
Orientation
Pourcentage_Blancs_et_nuls
Pourcentage_Abstentions
Pourcentage_Votants

In [52]:
df = pd.merge(df_pop_scol, df_elections, on=["Libellé de la commune"])

In [53]:
df.to_csv('combined_all.csv', index=False)