In [27]:
import pandas as pd

In [28]:
df_2009 = pd.read_csv('2009.csv')
df_2014 = pd.read_csv('2014.csv')
df_2020 = pd.read_csv('2020.csv')

/tmp/ipykernel_7633/3923221447.py:1: DtypeWarning: Columns (0,2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2009 = pd.read_csv('2009.csv')
/tmp/ipykernel_7633/3923221447.py:2: DtypeWarning: Columns (0,2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2014 = pd.read_csv('2014.csv')
/tmp/ipykernel_7633/3923221447.py:3: DtypeWarning: Columns (0,2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2020 = pd.read_csv('2020.csv')

In [29]:
# Most of the columns have the words 'en 2009' or 'en 2014' or 'en 2020' in them, so we can remove them
df_2009.columns = df_2009.columns.str.replace(' en 2009', '')
df_2014.columns = df_2014.columns.str.replace(' en 2014', '')
df_2020.columns = df_2020.columns.str.replace(' en 2020', '')

In [30]:
cols_2009 = df_2009.columns
cols_2014 = df_2014.columns
cols_2020 = df_2020.columns

# find the columns that are in all three dataframes
common_cols = list(set(cols_2009) & set(cols_2014) & set(cols_2020))

# filter the dataframes to only include the common columns
df_2009 = df_2009[common_cols]
df_2014 = df_2014[common_cols]
df_2020 = df_2020[common_cols]

In [31]:
# add year column to each dataframe
df_2009['year'] = 2009
df_2014['year'] = 2014
df_2020['year'] = 2020

In [32]:
# combine the dataframes
df = pd.concat([df_2009, df_2014, df_2020])

In [33]:
df.head()

,Pop scolarisée 25-29 ans (princ),Hommes 15-17 ans (princ),Hommes scolarisés 11-14 ans (princ),Pop 6-10 ans (princ),Hommes scolarisés 2-5 ans (princ),Hommes scolarisés 6-10 ans (princ),Femmes 15-17 ans (princ),Femmes scolarisées 11-14 ans (princ),Région,Département,...,Pop scolarisée 2-5 ans (princ),Pop scolarisée 11-14 ans (princ),Femmes scolarisées 25-29 ans (princ),Femmes 18-24 ans (princ),Pop 25-29 ans (princ),Hommes 25-29 ans (princ),Femmes 25-29 ans (princ),Hommes scolarisés 25-29 ans (princ),Pop 30 ans ou plus (princ),year
0,0.0,17.0,26.0,59.0,14.0,35.0,13.0,23.0,84,1,...,36.0,49.0,0.0,19.0,30.0,18.0,12.0,0.0,509.0,2009
1,0.0,2.0,1.0,19.0,7.0,11.0,3.0,5.0,84,1,...,9.0,6.0,0.0,7.0,15.0,9.0,6.0,0.0,137.0,2009
2,35.0,245.0,312.0,880.0,249.0,401.0,273.0,335.0,84,1,...,515.0,647.0,25.0,625.0,979.0,491.0,488.0,10.0,7788.0,2009
3,2.0,35.0,52.0,103.0,31.0,52.0,39.0,45.0,84,1,...,62.0,98.0,1.0,60.0,88.0,41.0,46.0,1.0,972.0,2009
4,0.0,4.0,3.0,4.0,1.0,1.0,3.0,0.0,84,1,...,2.0,3.0,0.0,0.0,7.0,2.0,5.0,0.0,88.0,2009

In [34]:
# remove all but gironde
df_gironde = df[df['Département'] == '33']

In [35]:
df_gironde.rename(columns={'Libellé géographique': 'Libellé de la commune'}, inplace=True)

/tmp/ipykernel_7633/3368248989.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gironde.rename(columns={'Libellé géographique': 'Libellé de la commune'}, inplace=True)

In [36]:
# save the combined dataframe to a new csv file
df_gironde.to_csv('combined.csv', index=False)